version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - mkdir target
      - touch target/email.html
      - chmod 755 target/email.html
      - echo "hello">>target/email.html
  post_build:
    commands:
      - echo " Bye Bye"
artifacts:
  files:
    - target/*
