version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo To Pull email template file 
      - ls 
  build:
    commands:
      - mkdir target
      - echo $SMTP_PASS is SMTP_PASS
      - echo $SMTP_ACCESS is SMTP_ACCESS
      - cat template.html>>target/email.html
  post_build:
    commands:
      - echo "Sending mail"
      - echo "Skipping python ./sendmail.py"
artifacts:
  files:
    - target/email.html
reports:
  Notification:
    files:
      - target/*
