version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo To Pull email template file 
      - ls 
  build:
    commands:
      - mkdir target
      - touch target/email.html
      - echo $SMTP_PASS is SMTP_PASS
      - echo $SMTP_ACCESS is SMTP_ACCESS
      - chmod 755 target/email.html
      - cat template.html>>target/email.html
  post_build:
    commands:
      - echo "Sending mail"
      - python sendmail.py
artifacts:
  files:
    - target/*
reports:
  Notification:
    files:
      - target/*
