version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - echo "email">email.html
  post_build:
    commands:
      - echo " Bye Bye"
artifacts:
  files:
    - email.html
