version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - mkdir target
      - touch target/email.html
      - echo $SMTP_PASS is SMTP_PASS
      - echo $SMTP_ACCESS is SMTP_ACCESS
      - chmod 755 target/email.html
      - cat template.html>>target/email.html
  post_build:
    commands:
      - echo " Bye Bye"
artifacts:
  files:
    - target/*
reports:
  Notification:
    files:
      - target/*
