version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - java -version
      - mvn package
  post_build:
    commands:
      - echo " Test ">>email.html
artifacts:
  files:
    - email.html
